version: '2'

services: 
  rabbit:
    image: "rabbitmq:3"
    hostname: rabbit
    ports:
      - "5672:5672"
    networks: 
      - appnet

  sql.data:
    image: "microsoft/mssql-server-linux"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word"
    ports:
      - "5433:1433"
    networks:
      - appnet
    volumes:
      - /var/opt/mssql

  data:
    build:
      context: ./Collaboration.Data
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    networks:
    - appnet
  
  collaboration.api:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - sql.data
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
    - appnet

networks:
  appnet:
    driver: bridge

  