version: '2'

services: 
  rabbit:
    image: "rabbitmq:management"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - appnet

  sql.data:
    image: "microsoft/mssql-server-linux"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - /var/opt/mssql

  data:
    build:
      context: ./Collaboration.Data
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    environment:
      ConnectionString: "Data Source=sql.data;Database=Collaboration;User Id=sa;Password=Pass@word"

    networks:
    - appnet
  
  collaboration.api:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - sql.data
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: "Data Source=sql.data;Database=Collaboration;User Id=sa;Password=Pass@word"
      EventBusConnection: rabbit
      EventBusUserName: "guest"
      EventBusPassword: "guest"
    networks:
    - appnet

networks:
  appnet:
    driver: bridge

  