version: '3'

services: 
  broker:
    image: "rabbitmq:latest"
    hostname: rabbit
    ports:
      - "5672:5672"
    networks: 
      - app-network
  app1:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - broker
    environment: 
      - ASPNETCORE_URLS="http://*:5000"
    networks:
    - app-network
  app2:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - broker
    environment:
      - ASPNETCORE_URLS="http://*:5001"
    networks:
    - app-network

  networks:
    graph-network:
      driver: bridge

  