version: '2'

services: 
  rabbit:
    image: "rabbitmq:management"
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - appnet

  mssqldb:
    image: "microsoft/mssql-server-linux"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - /var/opt/mssql

  data:
    build:
      context: ./Collaboration.Data
      dockerfile: Dockerfile
    depends_on:
      - mssqldb
    environment: 
      SQLSERVER_HOST: mssqldb
    networks:
    - appnet
  
  service1:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - mssqldb
    ports:
      - "5000:80"
    environment: 
      SQLSERVER_HOST: mssqldb  
    networks:
    - appnet

  service2:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - mssqldb
    ports:
      - "5001:80"
    environment: 
      SQLSERVER_HOST: mssqldb  
    networks:
    - appnet

networks:
  appnet:
    driver: bridge

  