version: '2'

services: 
  broker:
    image: "rabbitmq:latest"
    hostname: rabbit
    ports:
      - "5672:5672"
    networks: 
      - appnet

  mssqldb:
    image: "microsoft/mssql-server-linux"
    build: 
      context: ./Collaboration.Data
      dockerfile: Dockerfile 
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - /var/opt/mssql

  service1:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    depends_on:
      - broker
      - mssqldb
    ports:
      - "5000:5000"
    environment: 
      ASPNETCORE_URLS: "http://*:5000"
      SQLSERVER_HOST: mssqldb  
    networks:
    - appnet

  service2:
    build:
      context: ./Collaboration.Api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - broker
      - mssqldb
    environment:
      ASPNETCORE_URLS: "http://*:5001"
      SQLSERVER_HOST: mssqldb 
    networks:
    - appnet

networks:
  appnet:
    driver: bridge

  