apiVersion: v1
kind: Service
metadata:
  labels:
    app: innovationchallenge
    component: frontend
  name: frontend
spec:
  ports:
  - port: 80
  selector:
    app: innovationchallenge
    component: frontend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovationchallenge
      component: frontend  
  template:
    metadata:
      labels:
        app: innovationchallenge
        component: frontend
    spec:      
      containers:
      - name: frontend
        image: gfawcett22/rt-collab
        imagePullPolicy: Always
        ports:
        - containerPort: 80
