apiVersion: v1
kind: Service
metadata:
  labels:
    app: innovation-challenge
    component: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: eshop
    component: rabbitmq

---

apiVersion: v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    metadata:
      labels:
        app: innovation-challenge
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        ports:
        - containerPort: 5672